### ISSUE TITLE
关于反编译的问题？

### ISSUE THREAD

**Issue by po1ng** [ysc3839/bilibili-api#2]
能单独询问一下您关于如何在混淆代码中，找出B站oauth的认证方法的吗？ 我也尝试反编译apk来从客户端登录，但确实很难从混淆代码中找出sign参数的生成算法，特向您请教一下，麻烦了。

**Comment by ysc3839** [comment]
反编译是看运气的，当时旧版本混的没那么淆，于是找到了那段代码。
sign 算法来自其他项目。

**Comment by po1ng** [comment]
那请问一下app_secret这个参数是从编译文件里面获取的么？

**Comment by ysc3839** [comment]
@gogoforit 是的
